apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-db-env
  namespace: home-server
data:
  POSTGRES_USER: gitlab
  POSTGRES_DB: gitlabhq_production
  POSTGRES_PASSWORD: gitlab
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-env
  namespace: home-server
data:
  GITLAB_OMNIBUS_CONFIG: |
      postgresql['enable'] = false
      gitlab_rails['db_username'] = "gitlab"
      gitlab_rails['db_password'] = "gitlab"
      gitlab_rails['db_host'] = "postgresql"
      gitlab_rails['db_port'] = "5432"
      gitlab_rails['db_database'] = "gitlabhq_production"
      gitlab_rails['db_adapter'] = 'postgresql'
      gitlab_rails['db_encoding'] = 'utf8'
      gitlab_rails['lfs_enabled'] = true
      redis['enable'] = false
      gitlab_rails['redis_host'] = 'redis'
      gitlab_rails['redis_port'] = '6379'
      gitlab_rails['gitlab_shell_ssh_port'] = 22
      external_url 'http://gitlab.example.com'
