apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-db-env
  namespace: default
data:
  MYSQL_ROOT_PASSWORD: nextcloud
  MYSQL_USER: nextcloud
  MYSQL_DATABASE: nextcloud
  MYSQL_PASSWORD: nextcloud
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-env
  namespace: default
data:
  UID: '1000'
  GID: '1000'
  UPLOAD_MAX_SIZE: 10G
  APC_SHM_SIZE: 128M
  OPCACHE_MEM_SIZE: '128'
  REDIS_MAX_MEMORY: 64mb
  CRON_PERIOD: 15m
  TZ: CET
  ADMIN_USER: root
  ADMIN_PASSWORD: nextcloud
  DB_TYPE: mysql
  DB_NAME: nextcloud
  DB_USER: nextcloud
  DB_PASSWORD: nextcloud
  DB_HOST: nextcloud-db
